name: Release Automation

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: The scale of the version bump required for semver compatibility
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
concurrency: release

permissions: {}

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4096m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError" -Dkotlin.daemon.jvm.options="-Xmx2560m" -Dkotlin.incremental=false
  CI_GRADLE_ARG_PROPERTIES: --stacktrace -PpreDexEnable=false --max-workers 4 --no-daemon
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ANDROID_SIGNING_GPG }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ANDROID_SIGNING_KEY_ID }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
jobs:
  release:
    name: Release Bindings for Kotlin, Swift & Typescript
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
          token: ${{ secrets.ELEMENT_BOT_TOKEN }}
          # Need the credentials for pushing the version commit
          persist-credentials: true

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          cache: ""
          package-manager-cache: false

      - name: 🗜️ Setup
        run: "./scripts/setup.sh"

      - name: 🔨 Generate json
        run: "./scripts/generateJson.sh"

      - name: 👊 Bump yarn version
        run: |
          yarn version --no-git-tag-version --${GITHUB_EVENT_INPUTS_VERSION_BUMP}
        env:
          GITHUB_EVENT_INPUTS_VERSION_BUMP: ${{ github.event.inputs.version-bump }}

      - name: 👊 Set the version in env
        run: |
          echo "NEW_VERSION=$(cat package.json | jq -r .version)" >> $GITHUB_ENV

      - name: 👊 Sync the version with android
        run: |
          ./scripts/update_android_version.sh ${NEW_VERSION}

      - name: 👊 Commit the version
        run: |
          git config --global user.name 'ElementRobot'
          git config --global user.email 'releases@riot.im'
          git commit -am "${GITHUB_EVENT_INPUTS_VERSION_BUMP} version bump"
          git push
        env:
          GITHUB_EVENT_INPUTS_VERSION_BUMP: ${{ github.event.inputs.version-bump }}

      - name: 🛠️ Setup Java
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
        with:
          cache-disabled: true
      - name: ⬆️ Publish to Maven Central
        working-directory: platforms/android
        run: ./gradlew publishAllPublicationsToMavenCentral
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
        with:
          cache-disabled: true
      - name: 🚀 Close staging repo and release version
        working-directory: platforms/android
        run: ./gradlew publishAllPublicationsToMavenCentral

      - name: 🚀 Publish to npm
        id: npm-publish
        uses: JS-DevTools/npm-publish@5a85faf05d2ade2d5b6682bfe5359915d5159c6c # v2.2.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          ignore-scripts: false

      - name: 🧬 Create release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          body: ${{ env.NEW_VERSION }} Release
          draft: false
          prerelease: false
